### ISSUE TITLE
Is anyone using WebRTC yet?

### ISSUE THREAD

**Issue by simonwex** [mozilla/caravela#1]
Archiving this over time is the interesting piece here. Can we see WebRTC adoption happen over the next year?

**Comment by michaelrhanson** [comment]
http://gocast.it/ is using it.  They are pushing use of [their plugin](https://github.com/GoCast/webrtc_plugin) for browsers lacking support.

**Comment by michaelrhanson** [comment]
Hi Simon!  I have no idea if you actually want me to comment on these issues, but they showed up in my feed so there you go.  :P

m

**Comment by davidascher** [comment]
Funny.  @michaelrhanson This is actually a bug tracking a use case for a
project we're thinking of doing. Meaning, this is a question we want this
project to be able to answer, and even though the question as stated as a
binary, we don't really intend it as a binary.

(aside: how you doing?!)

**Comment by michaelrhanson** [comment]
Yup, I figured it was more of a tracker issue.  These guys were pushing WebRTC hard so I figured I'd flag 'em for you.

I'm doing okay!  Getting close to pulling the trigger on something, I think.

m

**Comment by simonwex** [comment]
Context is everything. Great to feel like you're still around, @michaelrhanson.
