### ISSUE TITLE
How are different UAs handled?

### ISSUE THREAD

**Issue by davidascher** [mozilla/caravela#10]
What % serve desktop vs. mobile vs. OS-specific versions?

What % promote android or iphone apps?

**Comment by jjnsn** [comment]
(The background here is that UA sniffing, especially with the mobile web, is absolutely rampant, on the order of 50%+ of sites)

What % of mobile-ready websites (ie those that send mobile-optimized content to iPhone and Android UAs) send it to Firefox OS or Fennec UAs?

To what extent are "responsive design" practices actually taking hold in the web mainstream (AFAICT its only newish startup sites doing it)

Is the content sent to User-Agent A "better" than the content sent to User-Agent B? Better defined in terms of adherence to HTML5 standards, use of newer techniques, sheer quantity of content, amount of graphics etc.
