### ISSUE TITLE
What is "the web"'s JavaScript style guide?

### ISSUE THREAD

**Issue by simonwex** [mozilla/caravela#17]
Could we extract the most popular placement of keywords, parentheses, whitespace formatting and indention practices?

**Comment by srobertson** [comment]
Interesting, wonder if jslint or some other project could be used for that.

On Sun, Mar 17, 2013 at 5:34 PM, Simon Wex notifications@github.com wrote:

> Could we extract the most popular placement of keywords, parentheses,
> whitespace formatting and indention practices?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/blink/issues/17
> .

## 

-- Scott

"There was a time when the internet answered all my questions. Now it just
repeats them. - SDR"
