### ISSUE TITLE
Delegates blink.mozillalabs.com subdomain to route 53

### ISSUE THREAD

**Issue by srobertson** [mozilla/caravela#18]
I've created the recordset group within route 53. Can you ensure that the mozillalabs.com properly delegates to it?

**Comment by simonwex** [comment]
@srobertson could you grab the servers listed in the Delegation Set?

**Comment by srobertson** [comment]
ns-1835.awsdns-37.co.uk
ns-952.awsdns-55.net
ns-1181.awsdns-19.org
ns-55.awsdns-06.com

**Comment by simonwex** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=858202

**Comment by simonwex** [comment]
dig blink.mozillalabs.com soa

; <<>> DiG 9.8.3-P1 <<>> blink.mozillalabs.com soa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12286
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 0

;; QUESTION SECTION:
;blink.mozillalabs.com.     IN  SOA

;; ANSWER SECTION:
blink.mozillalabs.com.  900 IN  SOA ns-1835.awsdns-37.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; AUTHORITY SECTION:
blink.mozillalabs.com.  600 IN  NS  ns-1181.awsdns-19.org.
blink.mozillalabs.com.  600 IN  NS  ns-55.awsdns-06.com.
blink.mozillalabs.com.  600 IN  NS  ns-952.awsdns-55.net.
blink.mozillalabs.com.  600 IN  NS  ns-1835.awsdns-37.co.uk.

;; Query time: 300 msec
;; SERVER: 10.22.75.40#53(10.22.75.40)
;; WHEN: Fri Apr  5 08:38:24 2013
;; MSG SIZE  rcvd: 236
