### ISSUE TITLE
We should rename

### ISSUE THREAD

**Issue by davidascher** [mozilla/caravela#19]
We were "first", but there's no point in keeping the blink name.  In particular the domain should _not_ be blink.

Ideas for other names?

**Comment by srobertson** [comment]
Arachnology?

**Comment by simonwex** [comment]
@srobertson, you're winning at the name game so far. -- It's a bit of a long word though.

**Comment by srobertson** [comment]
How about...

![image](https://f.cloud.github.com/assets/25101/399141/cd224d00-a868-11e2-9e49-a56d035c72cc.png)

**Comment by srobertson** [comment]
Mozilla "Surveyor" has a nice ring to it. Plenty of good iconery can be made from the tools they use

**Comment by simonwex** [comment]
@davidascher we've decided on "Caravela". We need to move forward with domain names etc so we're going with it.

From http://en.wikipedia.org/wiki/Caravel 

<blockquote>
Portuguese caravel. This was the standard model used by the Portuguese in their voyages of exploration. It was able to sail into the wind, unlike every other ship; this technique was called tacking. 
</blockquote>

This was the type of ship that was Magellan's Flagship in the first circumnavigation.

<blockquote>
The fleet provided by King Charles V included five ships: the flagship Trinidad (110 tons, crew 55), under Magellan's command; San Antonio (120 tons; crew 60) commanded by Juan de Cartagena; Concepcion (90 tons, crew 45) commanded by Gaspar de Quesada; Santiago (75 tons, crew 32) commanded by Juan Serrano; and Victoria (85 tons, crew 43), named after the church of Santa Maria de la Victoria de Triana, where Magellan took an oath of allegiance to Charles V, commanded by Luis Mendoza. Trinidad was a caravel, and all others rated as carracks (Spanish "carraca" or "nao"; Portuguese "nau").
</blockquote>
