### ISSUE TITLE
How much of the web is broken because web is broken because of mixed content blocking?

### ISSUE THREAD

**Issue by simonwex** [mozilla/caravela#37]
http://www.linuxtoday.com/security/mozilla-firefox-23-will-block-mixed-ssl-content.html

**Comment by simonwex** [comment]
@srobertson this would be a hugely interesting thing to know for a lot of moz people.

**Comment by srobertson** [comment]
@simonwex We can't answer yet because it appears common crawl does not crawl content served via HTTPS. I've setup a meeting with the Common Crawl folks to discuss if they'd be willing to help us access that data.
