### ISSUE TITLE
how quickly is "the web" responding to new browser features?

### ISSUE THREAD

**Issue by simonwex** [mozilla/caravela#5]
This might be a duplicate of other things already listed. How do we deal with that?

**Comment by srobertson** [comment]
I think this should be broken up into two new issues: I'm proposing
- Plot % of web using css tag by time 
- Plot % of web using javascript method call by time

Are there other "browser features" that aren't related to CSS in javascript? For example specific headers?

**Comment by srobertson** [comment]
Added actionable issues #43 and #46 and it seems this is a duplicate of #7
